### ISSUE TITLE
klaviyo API Key

### ISSUE THREAD

**Issue by rylanharper** [studio-otto/shop-base-components#27]
Hey there, thanks for this component library! I currently have a Sanity x Shopify project for a client and am working with the klaviyo Subscribe component. It works very well, but I am wondering if the correct ID is the Public API Key (Account > Settings > API Keys) or if its the newsletter List ID Key (Lists & Segments > Newsletter > Settings). Oddly enough I tested it out and both work seem to work.. However it may be that there is a delay in the time the newsletter signup email reaches the client so perhaps I am just using the wrong api key at the wrong times during development. 

I just want to confirm which API key/id should be used. Thanks!

**Comment by fbushell** [comment]
Hey @rylanharper! It is the List ID (https://www.klaviyo.com/list/:id/settings) List > Settings.

The "Klaviyo delay" is really annoying, I have run into the same issue more times than I want to admit. Hope that helps and let me know if you run into anything else!
